import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/admin.css',
                'resources/css/adminDashboard.css',
                'resources/css/adminAttendance.css',
                'resources/css/adminRecruitment.css',
                'resources/css/adminTraining.css',
                'resources/css/adminPerformance.css',
                'resources/css/adminDepartment.css',
                'resources/css/employeeWizard.css',
                'resources/css/adminPersonnel.css',
                'resources/css/joborder.css',
                'resources/css/employee.css',
                'resources/css/employeeDashboard.css',
                'resources/css/adminChatbot.css',
                'resources/css/adminPayroll.css',
                'resources/css/adminLeaveAndBenefits.css',
                'resources/css/topbarTheme.css',
                'resources/css/passSlip.css',
                'resources/css/travelOrder.css',
                'resources/js/app.js',
                'resources/js/employeeDashboard.js',
                'resources/js/personnel/employeeWizard.js',
                'resources/js/personnel/employeeWizardComplete.js',
                'resources/js/personnel/adminPersonnel.js',
                'resources/js/personnel/assignSchedule.js',
                'resources/js/personnel/bulkAssignSchedule.js',
                'resources/js/personnel/viewSchedules.js',
                'resources/js/attendance/adminAttendance.js',
                'resources/js/attendance/dtrDetailModal.js',
                'resources/js/attendance/editDtrModal.js',
                'resources/js/attendance/correctAttendanceModal.js',
                'resources/js/attendance/detailedDtrModal.js',
                'resources/js/attendance/successModal.js',
                'resources/js/attendance/attendance-settings-tab.js',
                'resources/js/leaveAndBenefits/adminLeaveAndBenefits.js',
                'resources/js/leaveAndBenefits/add-leave-type-modal.js',
                'resources/js/leaveAndBenefits/view-leave-type-modal.js',
                'resources/js/leaveAndBenefits/leave-types-tab.js',
                'resources/js/leaveAndBenefits/leave-requests-tab.js',
                'resources/js/leaveAndBenefits/leave-credits-tab.js',
                'resources/js/leaveAndBenefits/benefits-summary-tab.js',
                'resources/js/leaveAndBenefits/transaction-history-tab.js',
                'resources/js/leaveAndBenefits/csc-daily-accrual-tab.js',
                'resources/js/leaveAndBenefits/add-accrual-rate-modal.js',
                'resources/js/leaveAndBenefits/add-manual-credit-modal.js',
                'resources/js/leaveAndBenefits/migrate-leave-records-modal.js',
                'resources/js/adminDashboard.js',
                'resources/js/passSlip/passSlip.js',
                'resources/js/travelOrder/travelOrder.js',
                'resources/js/travelOrder/pending-orders-tab.js',
                'resources/js/travelOrder/approved-orders-tab.js',
                'resources/js/travelOrder/disapproved-orders-tab.js',
                'resources/js/travelOrder/viewTravelOrderModal.js',
                'resources/js/departments/adminDepartments.js',
                'resources/js/departments/bulkImportDepartment.js',
                'resources/js/departments/bulkImportDesignation.js'
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
