import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/admin/admin.css',
                'resources/css/admin/adminDashboard.css',
                'resources/css/admin/adminAttendance.css',
                'resources/css/admin/adminRecruitment.css',
                'resources/css/admin/adminTraining.css',
                'resources/css/admin/adminPerformance.css',
                'resources/css/admin/adminDepartment.css',
                'resources/css/admin/employeeWizard.css',
                'resources/css/admin/adminPersonnel.css',
                'resources/css/admin/viewEmployeeModal.css',
                'resources/css/joborder.css',
                'resources/css/employee/employee.css',
                'resources/css/employee/employeeDashboard.css',
                'resources/css/employee/employeePayslip.css',
                'resources/css/employee/employeeAttendance.css',
                'resources/css/employee/employeeLeaveAndBenefits.css',
                'resources/css/employee/employeeTravelOrder.css',
                'resources/css/employee/employeePassSlip.css',
                'resources/css/employee/employeeTraining.css',
                'resources/css/employee/employeeLeaveCalendar.css',
                'resources/css/admin/adminChatbot.css',
                'resources/css/admin/adminPayroll.css',
                'resources/css/admin/adminLeaveAndBenefits.css',
                'resources/css/admin/adminLeaveCalendar.css',
                'resources/css/topbarTheme.css',
                'resources/css/passSlip.css',
                'resources/css/travelOrder.css',
                'resources/css/admin/adminDeductions.css',
                'resources/css/admin/adminSettings.css',
                'resources/css/admin/adminReports.css',
                'resources/css/admin/attendanceScanner.css',
                'resources/css/admin/adminWebsite.css',
                'resources/css/admin/adminAudit.css',
                'resources/css/mayor/mayor.css',
                'resources/css/mayor/mayorDashboard.css',
                'resources/css/shared/aiAssistant.css',
                'resources/js/app.js',
                'resources/js/shared/appearance.js',
                'resources/js/shared/aiAssistant.js',
                'resources/js/employee/employeeDashboard.js',
                'resources/js/employee/employeePayslip.js',
                'resources/js/employee/employeeAttendance.js',
                'resources/js/employee/employeeLeaveAndBenefits.js',
                'resources/js/employee/employeeTravelOrder.js',
                'resources/js/employee/employeePassSlip.js',
                'resources/js/employee/employeeTraining.js',
                'resources/js/employee/leaveCalendar/leaveCalendar.js',
                'resources/js/admin/personnel/employeeWizard.js',
                'resources/js/admin/personnel/employeeWizardComplete.js',
                'resources/js/admin/personnel/employeeWizardValidation.js',
                'resources/js/admin/personnel/employeeWizardDocuments.js',
                'resources/js/admin/personnel/adminPersonnel.js',
                'resources/js/admin/personnel/viewEmployeeModal.js',
                'resources/js/admin/personnel/assignSchedule.js',
                'resources/js/admin/personnel/bulkAssignSchedule.js',
                'resources/js/admin/personnel/viewSchedules.js',
                'resources/js/admin/attendance/adminAttendance.js',
                'resources/js/admin/attendance/dtrDetailModal.js',
                'resources/js/admin/attendance/editDtrModal.js',
                'resources/js/admin/attendance/correctAttendanceModal.js',
                'resources/js/admin/attendance/detailedDtrModal.js',
                'resources/js/admin/attendance/successModal.js',
                'resources/js/admin/attendance/attendance-settings-tab.js',
                'resources/js/admin/attendance/attendanceScanner.js',
                'resources/js/admin/leaveAndBenefits/adminLeaveAndBenefits.js',
                'resources/js/admin/leaveAndBenefits/add-leave-type-modal.js',
                'resources/js/admin/leaveAndBenefits/view-leave-type-modal.js',
                'resources/js/admin/leaveAndBenefits/leave-types-tab.js',
                'resources/js/admin/leaveAndBenefits/leave-requests-tab.js',
                'resources/js/admin/leaveAndBenefits/leaveDetailModal.js',
                'resources/js/admin/leaveAndBenefits/leave-credits-tab.js',
                'resources/js/admin/leaveAndBenefits/benefits-summary-tab.js',
                'resources/js/admin/leaveAndBenefits/transaction-history-tab.js',
                'resources/js/admin/leaveAndBenefits/csc-daily-accrual-tab.js',
                'resources/js/admin/leaveAndBenefits/add-accrual-rate-modal.js',
                'resources/js/admin/leaveAndBenefits/add-manual-credit-modal.js',
                'resources/js/admin/leaveAndBenefits/migrate-leave-records-modal.js',
                'resources/js/admin/passSlip/passSlip.js',
                'resources/js/admin/passSlip/passSlipDecisionModal.js',
                'resources/js/admin/travelOrder/travelOrder.js',
                'resources/js/admin/travelOrder/pending-orders-tab.js',
                'resources/js/admin/travelOrder/approved-orders-tab.js',
                'resources/js/admin/travelOrder/disapproved-orders-tab.js',
                'resources/js/admin/travelOrder/viewTravelOrderModal.js',
                'resources/js/admin/travelOrder/travelDecisionModal.js',
                'resources/js/admin/leaveCalendar/leaveCalendar.js',
                'resources/js/admin/departments/adminDepartments.js',
                'resources/js/admin/departments/bulkImportDepartment.js',
                'resources/js/admin/departments/bulkImportDesignation.js',
                'resources/js/admin/dashboard/adminDashboard.js',
                'resources/js/admin/dashboard/pending-requests-card.js',
                'resources/js/admin/dashboard/top-performers-card.js',
                'resources/js/admin/dashboard/performerDetailsModal.js',
                'resources/js/admin/dashboard/charts.js',
                'resources/js/admin/dashboard/department-distribution-card.js',
                'resources/js/admin/dashboard/early-birds-card.js',
                'resources/js/admin/dashboard/employee-directory.js',
                'resources/js/admin/dashboard/bird-schedule-tooltip.js',
                'resources/js/admin/deductions/adminDeductions.js',
                'resources/js/admin/deductions/addDeductionTypeModal.js',
                'resources/js/admin/deductions/editDeductionTypeModal.js',
                'resources/js/admin/deductions/addLoanModal.js',
                'resources/js/admin/deductions/assignDeductionModal.js',
                'resources/js/admin/deductions/assignDeductionScheduleModal.js',
                'resources/js/admin/deductions/editEmployeeDeductionModal.js',
                'resources/js/admin/deductions/employee-deductions.js',
                'resources/js/admin/deductions/loan-types.js',
                'resources/js/admin/deductions/loans.js',
                'resources/js/admin/deductions/schedules.js',
                'resources/js/admin/payroll/adminPayroll.js',
                'resources/js/admin/payroll/payroll-register.js',
                'resources/js/admin/payroll/payslip-management.js',
                'resources/js/admin/payroll/generate-payroll.js',
                'resources/js/admin/payroll/payroll-result-modal.js',
                'resources/js/admin/payroll/payroll-status-modals.js',
                'resources/js/admin/payroll/payslip-detail-modal.js',
                'resources/js/admin/chatbot/adminChatbot.js',
                'resources/js/admin/settings/adminSettings.js',
                'resources/js/admin/website/adminWebsite.js',
                'resources/js/admin/audit/adminAudit.js',
                'resources/js/mayor/dashboard/mayorDashboard.js',
                'resources/js/mayor/personnel/mayorPersonnel.js',
                'resources/js/mayor/travelOrder/mayorTravelOrder.js',
                'resources/js/mayor/leave/mayorLeave.js',
                'resources/js/mayor/passSlip/mayorPassSlip.js'
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        // `php artisan serve` listens on 127.0.0.1 (IPv4). Left to itself Vite
        // binds to [::1] (IPv6) and writes that into public/hot, so every asset
        // on the page becomes a cross-origin request to a different loopback
        // stack — which is why edited CSS kept appearing not to take effect:
        // the browser served its cached copy and a normal reload never
        // revalidated. Pinning the host keeps both servers on one origin.
        host: '127.0.0.1',
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
