import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/admin/admin.css',
                'resources/css/admin/adminDashboard.css',
                'resources/css/admin/adminAttendance.css',
                'resources/css/admin/adminRecruitment.css',
                'resources/css/admin/adminTraining.css',
                'resources/css/admin/adminPerformance.css',
                'resources/css/admin/adminDepartment.css',
                'resources/css/admin/employeeWizard.css',
                'resources/css/admin/adminPersonnel.css',
                'resources/css/joborder.css',
                'resources/css/employee/employee.css',
                'resources/css/employee/employeeDashboard.css',
                'resources/css/employee/employeePayslip.css',
                'resources/css/employee/employeeAttendance.css',
                'resources/css/employee/employeeLeaveAndBenefits.css',
                'resources/css/admin/adminChatbot.css',
                'resources/css/admin/adminPayroll.css',
                'resources/css/admin/adminLeaveAndBenefits.css',
                'resources/css/topbarTheme.css',
                'resources/css/passSlip.css',
                'resources/css/travelOrder.css',
                'resources/css/admin/adminDeductions.css',
                'resources/js/app.js',
                'resources/js/employee/employeeDashboard.js',
                'resources/js/employee/employeePayslip.js',
                'resources/js/employee/employeeAttendance.js',
                'resources/js/employee/employeeLeaveAndBenefits.js',
                'resources/js/admin/personnel/employeeWizard.js',
                'resources/js/admin/personnel/employeeWizardComplete.js',
                'resources/js/admin/personnel/adminPersonnel.js',
                'resources/js/admin/personnel/assignSchedule.js',
                'resources/js/admin/personnel/bulkAssignSchedule.js',
                'resources/js/admin/personnel/viewSchedules.js',
                'resources/js/admin/attendance/adminAttendance.js',
                'resources/js/admin/attendance/dtrDetailModal.js',
                'resources/js/admin/attendance/editDtrModal.js',
                'resources/js/admin/attendance/correctAttendanceModal.js',
                'resources/js/admin/attendance/detailedDtrModal.js',
                'resources/js/admin/attendance/successModal.js',
                'resources/js/admin/attendance/attendance-settings-tab.js',
                'resources/js/admin/leaveAndBenefits/adminLeaveAndBenefits.js',
                'resources/js/admin/leaveAndBenefits/add-leave-type-modal.js',
                'resources/js/admin/leaveAndBenefits/view-leave-type-modal.js',
                'resources/js/admin/leaveAndBenefits/leave-types-tab.js',
                'resources/js/admin/leaveAndBenefits/leave-requests-tab.js',
                'resources/js/admin/leaveAndBenefits/leave-credits-tab.js',
                'resources/js/admin/leaveAndBenefits/benefits-summary-tab.js',
                'resources/js/admin/leaveAndBenefits/transaction-history-tab.js',
                'resources/js/admin/leaveAndBenefits/csc-daily-accrual-tab.js',
                'resources/js/admin/leaveAndBenefits/add-accrual-rate-modal.js',
                'resources/js/admin/leaveAndBenefits/add-manual-credit-modal.js',
                'resources/js/admin/leaveAndBenefits/migrate-leave-records-modal.js',
                'resources/js/admin/passSlip/passSlip.js',
                'resources/js/admin/travelOrder/travelOrder.js',
                'resources/js/admin/travelOrder/pending-orders-tab.js',
                'resources/js/admin/travelOrder/approved-orders-tab.js',
                'resources/js/admin/travelOrder/disapproved-orders-tab.js',
                'resources/js/admin/travelOrder/viewTravelOrderModal.js',
                'resources/js/admin/departments/adminDepartments.js',
                'resources/js/admin/departments/bulkImportDepartment.js',
                'resources/js/admin/departments/bulkImportDesignation.js',
                'resources/js/admin/dashboard/adminDashboard.js',
                'resources/js/admin/dashboard/pending-requests-card.js',
                'resources/js/admin/dashboard/top-performers-card.js',
                'resources/js/admin/dashboard/performerDetailsModal.js',
                'resources/js/admin/dashboard/charts.js',
                'resources/js/admin/dashboard/department-distribution-card.js',
                'resources/js/admin/dashboard/early-birds-card.js',
                'resources/js/admin/dashboard/viewEmployeeDashboardModal.js',
                'resources/js/admin/dashboard/employee-directory.js',
                'resources/js/admin/dashboard/addEmployeeModal.js',
                'resources/js/admin/dashboard/bird-schedule-tooltip.js',
                'resources/js/admin/deductions/adminDeductions.js',
                'resources/js/admin/deductions/addDeductionTypeModal.js',
                'resources/js/admin/deductions/editDeductionTypeModal.js',
                'resources/js/admin/deductions/addLoanModal.js',
                'resources/js/admin/deductions/assignDeductionModal.js',
                'resources/js/admin/deductions/assignDeductionScheduleModal.js',
                'resources/js/admin/deductions/editEmployeeDeductionModal.js',
                'resources/js/admin/deductions/employee-deductions.js',
                'resources/js/admin/deductions/loan-types.js',
                'resources/js/admin/deductions/loans.js',
                'resources/js/admin/deductions/schedules.js',
                'resources/js/admin/payroll/adminPayroll.js',
                'resources/js/admin/payroll/payroll-register.js',
                'resources/js/admin/payroll/payslip-management.js',
                'resources/js/admin/payroll/generate-payroll.js',
                'resources/js/admin/payroll/payroll-result-modal.js',
                'resources/js/admin/payroll/payroll-status-modals.js',
                'resources/js/admin/payroll/payslip-detail-modal.js',
                'resources/js/admin/chatbot/adminChatbot.js'
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
