{{-- PDF export for AI-generated reports. Rendered by dompdf, which supports a
     conservative subset of CSS: no flexbox, no grid, no CSS variables. Keep to
     tables and block layout here. --}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page { margin: 28px 26px 46px; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9.5px;
            color: #111827;
            margin: 0;
        }

        .masthead { border-bottom: 2px solid #111827; padding-bottom: 8px; margin-bottom: 14px; }
        .org { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: #6b7280; }
        h1 { font-size: 16px; margin: 4px 0 2px; }
        .period { font-size: 10px; color: #4b5563; }

        .totals { margin: 0 0 14px; width: 100%; border-collapse: collapse; }
        .totals td {
            border: 1px solid #e5e7eb;
            padding: 6px 8px;
            background: #f9fafb;
        }
        .totals .k { font-size: 8.5px; text-transform: uppercase; letter-spacing: 0.06em; color: #6b7280; }
        .totals .v { font-size: 13px; font-weight: bold; }

        table.data { width: 100%; border-collapse: collapse; }
        table.data th {
            background: #111827;
            color: #ffffff;
            text-align: left;
            padding: 6px 7px;
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        table.data td {
            padding: 5px 7px;
            border-bottom: 1px solid #e5e7eb;
        }
        table.data tr:nth-child(even) td { background: #f9fafb; }
        .right { text-align: right; }

        .chart { margin: 0 0 16px; }
        .empty { color: #6b7280; font-style: italic; padding: 18px 0; }

        .footer {
            position: fixed;
            bottom: -28px;
            left: 0;
            right: 0;
            font-size: 8px;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
            padding-top: 5px;
        }
        .footer .right { float: right; }
    </style>
</head>
<body>
    <div class="masthead">
        <div class="org">PRIME HRIS — Municipality of Magdalena</div>
        <h1>{{ $title }}</h1>
        @if ($period)
            <div class="period">Covering {{ $period['label'] ?? '' }}
                @if (!empty($period['start']) && !empty($period['end']))
                    ({{ $period['start'] }} to {{ $period['end'] }})
                @endif
            </div>
        @endif
    </div>

    @if (!empty($totals))
        <table class="totals">
            <tr>
                @foreach ($totals as $label => $value)
                    <td>
                        <div class="k">{{ $label }}</div>
                        <div class="v">{{ is_numeric($value) ? number_format((float) $value, fmod((float) $value, 1) == 0 ? 0 : 2) : $value }}</div>
                    </td>
                @endforeach
            </tr>
        </table>
    @endif

    @if ($chartSvg)
        <div class="chart">{!! $chartSvg !!}</div>
    @endif

    @if (empty($rows))
        <p class="empty">No records matched this report.</p>
    @else
        <table class="data">
            <thead>
                <tr>
                    @foreach ($columns as $column)
                        <th class="{{ ($column['align'] ?? '') === 'right' ? 'right' : '' }}">{{ $column['label'] }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                    <tr>
                        @foreach ($columns as $column)
                            @php
                                $value = $row[$column['key']] ?? '';
                                if (($column['format'] ?? null) === 'money' && is_numeric($value)) {
                                    $value = number_format((float) $value, 2);
                                }
                            @endphp
                            <td class="{{ ($column['align'] ?? '') === 'right' ? 'right' : '' }}">{{ $value }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by the PRIME HRIS AI Assistant for {{ $generatedBy }} on
        {{ \Illuminate\Support\Carbon::parse($generatedAt)->format('F j, Y g:i A') }}.
        <span class="right">{{ count($rows) }} record(s)</span>
    </div>
</body>
</html>
