<?php

namespace App\Http\Controllers;

use App\Models\SystemAiSetting;
use App\Models\UserThemeSetting;
use App\Services\SystemTheme;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Appearance — personal palettes for everyone, the organisation default for
 * administrators.
 *
 * Two scopes, deliberately separate endpoints rather than one endpoint with
 * a `scope` parameter: the global one is an administrator action and the
 * personal one is not, so the authorisation difference is visible in the
 * routing table instead of buried in a branch.
 *
 * Nothing here accepts CSS. The only inputs are a palette key checked
 * against SystemTheme::PALETTES and four six-digit hex colours; everything
 * the browser finally applies is generated by SystemTheme from those.
 */
class AppearanceController extends Controller
{
    /** Palette key + the optional colours, the only shape any endpoint takes. */
    private function validated(Request $request): array
    {
        $hex = 'regex:/^#[0-9a-fA-F]{6}$/';

        return $request->validate([
            'theme'        => ['required', 'string', 'in:' . implode(',', array_keys(SystemTheme::PALETTES))],
            'custom_color' => ['nullable', 'string', $hex],
            'secondary'    => ['nullable', 'string', $hex],
            'accent'       => ['nullable', 'string', $hex],
            'muted'        => ['nullable', 'string', $hex],
            // Named surfaces, not colours — only these three are accepted.
            'sidebar_style' => ['nullable', 'string', 'in:' . implode(',', array_keys(SystemTheme::SURFACE_STYLES))],
            'topbar_style'  => ['nullable', 'string', 'in:' . implode(',', array_keys(SystemTheme::SURFACE_STYLES))],
        ]);
    }

    /** @param array<string,mixed> $data */
    private function columns(array $data): array
    {
        return [
            'theme'                => $data['theme'],
            'custom_theme_primary' => $data['theme'] === 'custom' ? ($data['custom_color'] ?? null) : null,
            'theme_secondary'      => $data['secondary'] ?? null,
            'theme_accent'         => $data['accent'] ?? null,
            'theme_muted'          => $data['muted'] ?? null,
            'sidebar_style'        => $data['sidebar_style'] ?? SystemTheme::DEFAULT_SURFACE,
            'topbar_style'         => $data['topbar_style'] ?? SystemTheme::DEFAULT_SURFACE,
        ];
    }

    /**
     * Resolve a palette without saving it, so the picker previews live.
     *
     * Open to any signed-in user: it reads nothing and returns only colours
     * derived from the values posted. The derivation is contrast-checked
     * colour maths that must not be duplicated in JavaScript — a second
     * implementation would drift and the preview would then promise a
     * palette the server does not produce.
     */
    public function preview(Request $request)
    {
        $data = $this->validated($request);

        return response()->json([
            'success' => true,
            'vars'    => SystemTheme::resolve(
                $data['theme'],
                $data['custom_color'] ?? null,
                $data['secondary'] ?? null,
                $data['accent'] ?? null,
                $data['muted'] ?? null,
                $data['sidebar_style'] ?? null,
                $data['topbar_style'] ?? null,
            ),
        ]);
    }

    // ── Personal ─────────────────────────────────────────────────────────

    public function updatePersonal(Request $request)
    {
        $data = $this->validated($request);

        UserThemeSetting::updateOrCreate(
            ['user_id' => Auth::id()],
            $this->columns($data),
        );
        SystemTheme::flushCache();

        return response()->json([
            'success' => true,
            'message' => 'Your appearance has been updated.',
            'source'  => 'personal',
        ]);
    }

    /**
     * Drop the personal palette so the organisation's takes over again.
     * A delete, not a flag: the absence of a row is the "system theme"
     * state everywhere else in the feature.
     */
    public function resetPersonal()
    {
        UserThemeSetting::where('user_id', Auth::id())->delete();
        SystemTheme::flushCache();

        return response()->json([
            'success' => true,
            'message' => 'Your appearance now follows the system theme.',
            'source'  => 'system',
        ]);
    }

    // ── Global (administrators only) ──────────────────────────────────────

    private function denyNonAdmin(): ?\Illuminate\Http\JsonResponse
    {
        // Backend check, not a hidden button: the UI omits this section for
        // non-admins, but the endpoint is what actually enforces it.
        return Auth::user()->hasRole('admin')
            ? null
            : response()->json([
                'success' => false,
                'message' => 'Only administrators can change the system theme.',
            ], 403);
    }

    public function updateGlobal(Request $request)
    {
        if ($denied = $this->denyNonAdmin()) {
            return $denied;
        }

        $data = $this->validated($request);
        SystemAiSetting::current()->update($this->columns($data));
        SystemTheme::flushCache();

        return response()->json([
            'success' => true,
            'message' => 'System theme updated. Users with their own appearance keep it.',
        ]);
    }

    /**
     * Restore the shipped default. This never touches user_theme_settings —
     * resetting the organisation's palette must not silently discard what
     * individual people chose for themselves.
     */
    public function resetGlobal()
    {
        if ($denied = $this->denyNonAdmin()) {
            return $denied;
        }

        SystemAiSetting::current()->update([
            'theme'                => 'default',
            'custom_theme_primary' => null,
            'theme_secondary'      => null,
            'theme_accent'         => null,
            'theme_muted'          => null,
            'sidebar_style'        => SystemTheme::DEFAULT_SURFACE,
            'topbar_style'         => SystemTheme::DEFAULT_SURFACE,
        ]);
        SystemTheme::flushCache();

        return response()->json([
            'success' => true,
            'message' => 'System theme restored to the PRIME HRIS default.',
        ]);
    }
}
