<?php

namespace Tests\Unit;

use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * The Add Employee wizard must not accept a password.
 *
 * A hand-typed password is chosen by the admin, reused across the accounts they
 * create, and known to them afterwards — and it was mailed in plaintext, so one
 * leaked email described the shape of the next hire's login too. The password is
 * now generated by `TemporaryPasswordService` and reaches the employee only
 * through the credentials email.
 *
 * Nothing but these files connects the two halves: the form, the controller that
 * reads it, and the generator. A reinstated `<input name="password">` would be
 * silently ignored by the controller (nothing validates or reads it) while
 * telling the admin they are choosing the password — which is worse than either
 * behaviour on its own. So the absence is pinned here rather than assumed.
 *
 * These read the files, like `PersonnelEmailNoticeTest`: there is no HTTP
 * fixture for a seven-step file-upload wizard, and `RefreshDatabase` does not
 * work in this project.
 */
class EmployeePasswordGenerationTest extends TestCase
{
    private function wizard(): string
    {
        return file_get_contents(
            resource_path('views/admin/personnel/modals/employeeWizardComplete.blade.php')
        );
    }

    private function controller(): string
    {
        return file_get_contents(
            app_path('Http/Controllers/EmployeeRegistrationController.php')
        );
    }

    #[Test]
    public function the_wizard_renders_no_password_input(): void
    {
        $wizard = $this->wizard();

        $this->assertStringNotContainsString('name="password"', $wizard);
        $this->assertStringNotContainsString('name="password_confirm"', $wizard);
        $this->assertStringNotContainsString('type="password"', $wizard);
    }

    /**
     * Removing the field is only half of it: the admin has to be told where the
     * password goes instead, or the form looks like it will create an account
     * nobody can sign in to.
     */
    #[Test]
    public function the_wizard_says_the_password_is_generated_and_emailed(): void
    {
        $wizard = $this->wizard();

        $this->assertStringContainsString('TemporaryPasswordService::LENGTH', $wizard);
        $this->assertMatchesRegularExpression('/random[^<]*password/i', $wizard);
        $this->assertMatchesRegularExpression('/email[^<]*address above/i', $wizard);
    }

    /**
     * The length in that sentence is read off the generator, so the copy cannot
     * promise eight characters while the service issues twelve.
     */
    #[Test]
    public function the_stated_length_comes_from_the_generator(): void
    {
        $this->assertStringContainsString('\\App\\Services\\TemporaryPasswordService::LENGTH', $this->wizard());
    }

    /**
     * The regression: an admin submitting a password and it being used. The
     * controller must not read the request for one, whatever the form sends.
     */
    #[Test]
    public function the_controller_never_reads_a_submitted_password(): void
    {
        $controller = $this->controller();

        $this->assertStringNotContainsString('$request->password', $controller);
        $this->assertStringContainsString('TemporaryPasswordService::generate()', $controller);
    }

    /**
     * Bulk import used to fall back to the literal 'password123' when a row's
     * Password cell was blank — one guessable password shared by every account
     * imported that way, printed in each of their emails.
     */
    #[Test]
    public function bulk_import_has_no_shared_default_password(): void
    {
        $this->assertStringNotContainsString('password123', $this->controller());
    }
}
