<?php

namespace App\Services;

/**
 * SystemTheme — the whole UI's colour system, derived from one seed colour.
 *
 * Every palette (including the admin's own custom hex) is generated by
 * `derive()` from a single seed, so a theme is never a bag of hand-picked
 * hexes that happen to sit near each other. Three properties follow, and they
 * are the reason this is arithmetic rather than a lookup table:
 *
 *  1. **One hue runs through the entire UI.** The palettes used to recolour
 *     only `--gp-pri` / `--gp-pri-2` / `--c-blue`, while `--gp-bg`,
 *     `--gp-ink`, `--gp-border` and the tint ramp stayed the brand's
 *     navy-lavender. Picking "Emerald Green" gave a green sidebar sitting on
 *     lavender page tints with navy body text — the mismatch that made a
 *     changed theme look broken rather than restyled. The neutral ramp is now
 *     derived from the seed hue too.
 *  2. **Foregrounds are measured, never assumed.** Text colour on any filled
 *     surface comes from `readableOn()`, which compares WCAG contrast against
 *     white and against the theme's own ink. The old code hard-coded
 *     `#ffffff` on every button, so a light seed (gold, sky, lime) produced
 *     white-on-pale buttons that could not be read at all.
 *  3. **Saturation and lightness are clamped into a usable band.** A seed is
 *     a direction, not a literal fill: `#ffe600` becomes a deep gold anchor
 *     with a bronze action colour, because no interface can carry body text
 *     on pure yellow. Greys stay grey — the chroma floor is a floor on the
 *     *seed's* chroma, not a forced injection of colour.
 *
 * `derive()` reproduces the original navy values to within a few RGB points,
 * so the default theme is unchanged while every other palette gains the same
 * treatment.
 */
class SystemTheme
{
    /** WCAG AA for normal text. Filled surfaces that carry labels must clear it. */
    private const AA_CONTRAST = 4.5;

    /** WCAG AA for large text / UI boundaries. */
    private const AA_LARGE_CONTRAST = 3.0;

    /**
     * Built-in palettes. A palette is a seed plus a name — everything else is
     * derived, so palettes cannot drift from one another in quality.
     *
     * Keys are persisted in `system_ai_settings.theme`; renaming one orphans
     * whatever the municipality has already applied.
     */
    public const PALETTES = [
        'default' => ['label' => 'Municipal Navy', 'seed' => '#0b044d', 'blurb' => 'System default'],
        'indigo'  => ['label' => 'Indigo',         'seed' => '#312e81', 'blurb' => 'Calm, corporate'],
        'teal'    => ['label' => 'Deep Teal',      'seed' => '#115e59', 'blurb' => 'Cool and clinical'],
        'emerald' => ['label' => 'Emerald Green',  'seed' => '#064e3b', 'blurb' => 'Fresh, natural'],
        'amber'   => ['label' => 'Amber Gold',     'seed' => '#78350f', 'blurb' => 'Warm, ceremonial'],
        'crimson' => ['label' => 'Crimson Red',    'seed' => '#7f1d1d', 'blurb' => 'Bold, authoritative'],
        'rose'    => ['label' => 'Rose',           'seed' => '#9f1239', 'blurb' => 'Soft, approachable'],
        'violet'  => ['label' => 'Violet Purple',  'seed' => '#4c1d95', 'blurb' => 'Modern, distinct'],
        'slate'   => ['label' => 'Slate Gray',     'seed' => '#1e293b', 'blurb' => 'Neutral, understated'],
        'custom'  => ['label' => 'Custom Color',  'seed' => '#6366f1', 'blurb' => 'Pick any color'],
    ];

    public const DEFAULT_CUSTOM_SEED = '#6366f1';

    /**
     * Lightness for each numbered step, Tailwind-style 50→950.
     *
     * These are not round numbers for their own sake: they are the
     * lightnesses the hand-written stylesheets already clustered around
     * (98, 95, 93, 91, 84, 72, 62, 47, 35, 22, 16). Choosing the steps to
     * match existing usage is what let ~1,200 hard-coded literals be swapped
     * for variables without the pages shifting.
     */
    public const RAMP_STEPS = [
        50  => 0.980,
        100 => 0.960,
        200 => 0.935,
        300 => 0.905,
        400 => 0.840,
        500 => 0.720,
        600 => 0.620,
        700 => 0.470,
        800 => 0.350,
        900 => 0.220,
        950 => 0.150,
    ];

    /**
     * How the two big chrome surfaces — the sidebar and the topbar banner —
     * are filled. A named choice rather than a colour picker: "Dark" is a
     * decision anyone can make, "#111827" is not.
     *
     * Everything sitting on the surface (nav labels, hover fills, borders)
     * is derived from it by contrast, so choosing Light automatically turns
     * the nav text dark instead of leaving white-on-white.
     */
    public const SURFACE_STYLES = [
        'brand' => 'Theme colour',
        'dark'  => 'Dark',
        'light' => 'Light',
    ];

    public const DEFAULT_SURFACE = 'brand';

    /**
     * Semantic hue + saturation. Fixed, deliberately: a green that drifts
     * toward the active theme stops reading as "approved". Only their
     * lightness and their tint partners are derived.
     */
    public const SEMANTIC_HUES = [
        'success' => [142.0, 0.62],
        'danger'  => [4.0,   0.66],
        'warning' => [43.0,  0.72],
        'info'    => [201.0, 0.68],
    ];

    // ─────────────────────────────────────────────────────────────────
    //  Public API
    // ─────────────────────────────────────────────────────────────────

    public static function get(string $key): array
    {
        return self::PALETTES[$key] ?? self::PALETTES['default'];
    }

    public static function seedFor(string $key, ?string $customHex = null): string
    {
        if ($key === 'custom') {
            return self::isHex($customHex) ? strtolower($customHex) : self::DEFAULT_CUSTOM_SEED;
        }

        return self::get($key)['seed'];
    }

    /**
     * The complete variable map for a theme, with the admin's overrides
     * folded in and re-checked for contrast.
     *
     * @return array<string,string>
     */
    public static function resolve(
        string  $key,
        ?string $customHex    = null,
        ?string $secondary    = null,
        ?string $accent       = null,
        ?string $muted        = null,
        ?string $sidebarStyle = null,
        ?string $topbarStyle  = null
    ): array {
        $seed = self::seedFor($key, $customHex);
        $vars = self::derive($seed);

        // Chrome surfaces. Applied here rather than in derive() because they
        // are a stored preference alongside the overrides, not a property of
        // the seed colour.
        $vars = array_merge(
            $vars,
            self::surfaceVars('sidebar', $sidebarStyle, $seed, $vars),
            self::surfaceVars('topbar', $topbarStyle, $seed, $vars),
        );

        // ── Secondary: the lighter half of every brand gradient, the active
        //    tab fill and the pagination highlight.
        if (self::isHex($secondary)) {
            $vars['--theme-primary-2'] = strtolower($secondary);
        }

        // ── Accent: links, focus rings, primary buttons. An override may be
        //    any colour the admin likes, so the label sitting on it is
        //    recomputed rather than left as white.
        if (self::isHex($accent)) {
            $accent = strtolower($accent);
            $vars['--theme-accent']         = $accent;
            $vars['--theme-link']           = $accent;
            $vars['--theme-btn-primary-bg'] = $accent;
            $vars['--theme-btn-primary-fg'] = self::readableOn($accent, $vars['--theme-ink']);
            $vars['--theme-focus-ring']     = self::rgba($accent, 0.18);
        }

        // ── Muted: stat labels, table subtitles, sidebar nav text. This is a
        //    *text* tone, so it overrides `--theme-muted` (the neutral ramp),
        //    not `--theme-primary-muted` (the brand chip fill).
        if (self::isHex($muted)) {
            $vars['--theme-muted'] = strtolower($muted);
        }

        return self::withConsumerAliases($vars);
    }

    public static function toCss(
        string  $key,
        ?string $customHex    = null,
        ?string $secondary    = null,
        ?string $accent       = null,
        ?string $muted        = null,
        ?string $sidebarStyle = null,
        ?string $topbarStyle  = null
    ): string {
        return self::cssFrom(
            self::resolve($key, $customHex, $secondary, $accent, $muted, $sidebarStyle, $topbarStyle)
        );
    }

    /**
     * The saved palette as a `:root` block, for a layout's <style> tag.
     *
     * Every layout needs the same five arguments out of the same row, so
     * asking each one to assemble the call was five chances to pass them in
     * a different order. This is the one entry point layouts should use.
     *
     * The theme is organisation-wide: it lives on `system_ai_settings` and
     * there is no per-user theme column, so every signed-in user — and the
     * login screen, which has no user at all — gets this same palette.
     */
    public static function activeCss(): string
    {
        return self::cssFrom(self::activeVars());
    }

    /** @param array<string,string> $vars */
    private static function cssFrom(array $vars): string
    {
        $lines = array_map(fn ($k, $v) => "    $k: $v;", array_keys($vars), $vars);

        return ":root {\n" . implode("\n", $lines) . "\n}";
    }

    /**
     * Palette list for the picker. Each entry carries the swatch trio the card
     * renders, so the picker shows the palette that will actually be applied
     * instead of one seed blob and a raw hex string.
     *
     * `$customSeed` is the colour the admin has already saved, so the Custom
     * card previews their colour rather than the placeholder seed.
     */
    public static function all(?string $customSeed = null): array
    {
        return array_map(function ($key, $palette) use ($customSeed) {
            $vars = self::derive($key === 'custom' ? self::seedFor('custom', $customSeed) : $palette['seed']);

            return [
                'key'       => $key,
                'label'     => $palette['label'],
                'blurb'     => $palette['blurb'],
                'seed'      => $key === 'custom' ? self::seedFor('custom', $customSeed) : $palette['seed'],
                'preview'   => $vars['--theme-primary'],
                'swatches'  => [
                    $vars['--theme-primary'],
                    $vars['--theme-accent'],
                    $vars['--theme-primary-border'],
                ],
                // Pre-filled values for the override pickers, so the JS does
                // not keep its own copy of the palette table. These must name
                // the same variables `resolve()` writes an override onto, or
                // the picker opens on a colour the override would not replace.
                'defaults'  => [
                    'secondary' => $vars['--theme-primary-2'],
                    'accent'    => $vars['--theme-accent'],
                    'muted'     => $vars['--theme-muted'],
                ],
            ];
        }, array_keys(self::PALETTES), self::PALETTES);
    }

    /** Kept for callers that derived a palette straight from a hex. */
    public static function fromHex(string $hex): array
    {
        return self::withConsumerAliases(self::derive($hex));
    }

    /**
     * The palette the current viewer should see.
     *
     *     personal theme  →  global theme  →  application default
     *
     * A user's own row wins, so an admin changing the organisation's palette
     * never overwrites what someone has chosen for themselves. Having no row
     * *is* "use the system theme" — see UserThemeSetting.
     *
     * Memoised per request: the dashboards ask for this once per chart and
     * it cannot change mid-request.
     *
     * @return array<string,string>
     */
    public static function activeVars(): array
    {
        return self::$activeMemo ??= self::personalVars() ?? self::globalVars();
    }

    /** @var array<string,string>|null */
    private static ?array $activeMemo = null;

    /** @var \App\Models\UserThemeSetting|null|false false = not looked up yet. */
    private static $personalMemo = false;

    /**
     * Drop the per-request memo.
     *
     * Needed whenever the theme changes inside the request that reads it —
     * saving a palette, or a test acting as several requests in one process.
     */
    public static function flushCache(): void
    {
        self::$activeMemo = null;
        self::$personalMemo = false;
    }

    /**
     * The signed-in user's own palette, or null when they have not set one.
     *
     * @return array<string,string>|null
     */
    public static function personalVars(): ?array
    {
        $personal = self::personalSetting();

        return $personal ? self::resolveSetting($personal) : null;
    }

    /**
     * The organisation-wide palette, which is also the application default.
     *
     * A palette is cosmetic, so it may never be the reason a page cannot be
     * served. Every layout — including the login screen and the public
     * welcome page — renders `activeCss()`, so an unreachable or unmigrated
     * `system_ai_settings` used to turn one missing table into a 500 on
     * every route in the application. It now falls back to the shipped
     * default and reports the failure instead.
     */
    public static function globalVars(): array
    {
        try {
            return self::resolveSetting(\App\Models\SystemAiSetting::current());
        } catch (\Illuminate\Database\QueryException $e) {
            report($e);

            return self::withConsumerAliases(self::derive(self::PALETTES['default']['seed']));
        }
    }

    /** Whether the viewer is looking at a palette they chose themselves. */
    public static function hasPersonalTheme(): bool
    {
        return self::personalSetting() !== null;
    }

    /**
     * The current user's theme row. Guests and users without one get null,
     * which is what makes the login screen render the organisation palette.
     */
    public static function personalSetting(): ?\App\Models\UserThemeSetting
    {
        if (self::$personalMemo === false) {
            $id = \Illuminate\Support\Facades\Auth::id();

            try {
                self::$personalMemo = $id
                    ? \App\Models\UserThemeSetting::where('user_id', $id)->first()
                    : null;
            } catch (\Illuminate\Database\QueryException $e) {
                // Same rule as globalVars(): no personal palette is a
                // survivable state, an unservable page is not.
                report($e);
                self::$personalMemo = null;
            }
        }

        return self::$personalMemo;
    }

    /**
     * Everything the appearance picker needs, for one scope.
     *
     * `personal` opens on the user's own palette when they have one, and
     * otherwise on the organisation's — so the picker starts from what they
     * are actually looking at rather than from a blank slate.
     *
     * @param  'personal'|'global'  $scope
     * @return array<string,mixed>
     */
    public static function pickerPayload(string $scope): array
    {
        $global   = \App\Models\SystemAiSetting::current();
        $personal = self::personalSetting();

        $isPersonal = $scope === 'personal';
        $source     = $isPersonal ? ($personal ?? $global) : $global;
        $globalVars = self::resolveSetting($global);

        // With no personal row the "System theme" card is the selected one;
        // the preset cards still open on the organisation's values so a
        // first-time visitor sees where they are starting from.
        $selected = $isPersonal && ! $personal ? 'inherit' : ($source->theme ?? 'default');
        $custom   = $source->custom_theme_primary ?? self::DEFAULT_CUSTOM_SEED;

        return [
            'scope'        => $scope,
            'selected'     => $selected,
            'customColor'  => $custom,
            'secondary'    => $source->theme_secondary,
            'accent'       => $source->theme_accent,
            'muted'        => $source->theme_muted,
            'sidebarStyle' => $source->sidebar_style ?? self::DEFAULT_SURFACE,
            'topbarStyle'  => $source->topbar_style ?? self::DEFAULT_SURFACE,
            'palettes'     => self::all($custom),
            'usingPersonal' => $personal !== null,
            // The palette a "System theme" choice would hand back, for the
            // inherit card's swatch and for previewing that option.
            'globalTheme'    => $global->theme ?? 'default',
            'globalLabel'    => self::get($global->theme ?? 'default')['label'],
            'globalSwatches' => [
                $globalVars['--theme-primary'],
                $globalVars['--theme-accent'],
                $globalVars['--theme-primary-border'],
            ],
        ];
    }

    /** Resolve any record carrying the five theme columns. */
    private static function resolveSetting(object $setting): array
    {
        return self::resolve(
            $setting->theme ?? 'default',
            $setting->custom_theme_primary ?? null,
            $setting->theme_secondary ?? null,
            $setting->theme_accent ?? null,
            $setting->theme_muted ?? null,
            $setting->sidebar_style ?? null,
            $setting->topbar_style ?? null,
        );
    }

    /**
     * Chart series colours, named by role and returned in the order given.
     *
     * Order is load-bearing on some charts — an attendance chart whose first
     * series is "absent" wants red in slot 0, not the brand — so this takes
     * an explicit sequence rather than returning a fixed list to slice.
     *
     * A `#hex` argument passes through untouched. That is deliberate: the
     * brand and semantic slots should follow the theme, but the categorical
     * tail exists to tell one department from another, and re-tinting those
     * toward the theme is exactly how a legend stops being readable.
     *
     * @return list<string>
     */
    public static function series(string ...$roles): array
    {
        $vars = self::activeVars();

        return array_map(function (string $role) use ($vars): string {
            if (str_starts_with($role, '#')) {
                return $role;
            }

            return $vars["--theme-$role"] ?? $vars['--theme-primary'];
        }, $roles);
    }

    // ─────────────────────────────────────────────────────────────────
    //  Derivation
    // ─────────────────────────────────────────────────────────────────

    /**
     * Build every theme variable from one seed colour.
     *
     * @return array<string,string>
     */
    public static function derive(string $seed): array
    {
        if (!self::isHex($seed)) {
            $seed = self::PALETTES['default']['seed'];
        }

        [$h, $s, $l] = self::hexToHsl($seed);

        // A seed with no chroma of its own (white, black, any pure grey) must
        // stay achromatic. Without this the floors below would inject the
        // hue that `hexToHsl` reports for an achromatic colour — zero, i.e.
        // red — and a grey pick would come back faintly pink.
        $neutralSeed = $s < 0.02;

        /** Saturation for a derived tone, held to zero for an achromatic seed. */
        $sat = fn (float $factor, float $min, float $max): float => $neutralSeed
            ? 0.0
            : self::clamp($s * $factor, $min, $max);

        // Chroma envelope. The floor is deliberately low so a grey-ish seed
        // (Slate) stays restrained; the ceiling keeps a neon seed from
        // turning large fills into a screen full of vibrating colour.
        $chroma = $sat(1.0, 0.06, 0.90);

        // ── 1. Anchor: sidebar, page headers, brand gradients. Pulled into a
        //    dark band so it can carry white text whatever the seed's own
        //    lightness was. The band alone is not enough — lightness is not
        //    perceptual, so yellow and lime at L=0.28 still fail AA against
        //    white where navy passes comfortably. The clamp sets the ceiling
        //    and the contrast walk finds the shade that actually works.
        $primary  = self::darkenUntilReadable($h, $chroma, self::clamp($l, 0.15, 0.28));
        $anchorL  = self::hexToHsl($primary)[2];

        // The lighter half of every brand gradient. It carries text at the
        // edges of a gradient fill, so it is held to AA-large.
        $primary2 = self::darkenUntilReadable(
            $h,
            $chroma * 0.93,
            $anchorL + 0.09,
            self::AA_LARGE_CONTRAST
        );

        // ── 2. Action: buttons, links, focus rings. The lightest — therefore
        //    most vivid — shade of the seed hue that still carries white text
        //    at AA. Chroma is capped lower than the anchor's: a saturated
        //    action colour reads as a warning, not as a control.
        $accent = self::darkenUntilReadable($h, $sat(1.0, 0.06, 0.72), 0.46);

        // ── 3. Ink and the neutral ramp, tinted with the seed hue. This is
        //    what makes a theme change look designed rather than partial:
        //    page background, borders, table zebra and body text all carry a
        //    trace of the same hue as the sidebar.
        $ink      = self::hsl($h, $sat(0.45, 0.18, 0.42), 0.20);
        $textMid  = self::hsl($h, $sat(0.20, 0.10, 0.26), 0.40);
        $textSoft = self::hsl($h, $sat(0.18, 0.08, 0.22), 0.62);
        $mutedTxt = self::hsl($h, $sat(0.15, 0.07, 0.20), 0.55);
        $bg       = self::hsl($h, $sat(0.50, 0.10, 0.45), 0.975);
        $tint     = self::hsl($h, $sat(0.55, 0.10, 0.50), 0.972);
        $tint2    = self::hsl($h, $sat(0.60, 0.10, 0.55), 0.958);
        $border   = self::hsl($h, $sat(0.50, 0.08, 0.45), 0.935);

        // ── 4. Brand tints: stat-icon backgrounds, hover fills, chips.
        $light = self::hsl($h, $sat(1.0, 0.12, 0.85), 0.955);
        $soft  = self::hsl($h, $sat(1.0, 0.12, 0.85), 0.972);
        $edge  = self::hsl($h, $sat(1.0, 0.12, 0.70), 0.870);

        // `--theme-primary-muted` fills disabled states and de-emphasised
        // chips, so it needs to stay distinguishable from both the tints
        // above and the page background.
        $brandMuted = self::hsl($h, $sat(0.55, 0.12, 0.55), 0.70);

        // ── 5. Sidebar label colour, lifted until it clears AA against the
        //    sidebar it sits on rather than assumed to be light enough.
        $sidebarText = self::lightenUntilReadable($h, $sat(0.45, 0.12, 0.50), 0.78, $primary);

        $vars = [
            // Brand
            '--theme-primary'        => $primary,
            '--theme-primary-2'      => $primary2,
            '--theme-primary-light'  => $light,
            '--theme-primary-border' => $edge,
            '--theme-primary-muted'  => $brandMuted,
            '--theme-primary-soft'   => $soft,
            '--theme-accent'         => $accent,
            '--theme-link'           => $accent,

            // Filled surfaces + their measured foregrounds
            '--theme-on-primary'     => self::readableOn($primary, $ink),
            // Triplet form, for the translucent layers stacked on a brand
            // fill (the wizard header's step circles and connectors).
            '--theme-on-primary-rgb' => self::rgbTriplet(self::readableOn($primary, $ink)),
            '--theme-sidebar-bg'     => $primary,
            '--theme-sidebar-text'   => $sidebarText,
            '--theme-sidebar-active' => self::readableOn($primary, $ink),
            '--theme-btn-primary-bg' => $accent,
            '--theme-btn-primary-fg' => self::readableOn($accent, $ink),
            '--theme-stat-icon-bg'   => $light,
            '--theme-stat-icon-fg'   => $primary,
            '--theme-focus-ring'     => self::rgba($accent, 0.18),

            // Neutral ramp
            '--theme-ink'            => $ink,
            '--theme-text-mid'       => $textMid,
            '--theme-text-soft'      => $textSoft,
            '--theme-muted'          => $mutedTxt,
            '--theme-bg'             => $bg,
            '--theme-bg-tint'        => $tint,
            '--theme-bg-tint-2'      => $tint2,
            '--theme-border'         => $border,
        ];

        // ── 6. Numbered ramps, so a stylesheet can reach for a step by weight
        //    instead of inventing another literal. The steps are the
        //    lightnesses the hand-written CSS was already clustering around,
        //    which is what lets those literals be swapped for a variable
        //    without the page shifting.
        foreach (self::RAMP_STEPS as $step => $stepL) {
            // Tints stay less saturated than fills: a pale step at full
            // chroma reads as a tinted error state rather than a surface.
            $weight = $stepL > 0.90 ? 0.55 : ($stepL > 0.70 ? 0.80 : 1.0);
            $vars["--theme-primary-$step"] = self::hsl($h, $sat($weight, 0.10, 0.85), $stepL);
            $vars["--theme-neutral-$step"] = self::hsl($h, $sat(0.18, 0.04, 0.18), $stepL);
        }

        // ── 7. Semantic colours. Their hues are fixed — a green "approved"
        //    badge that drifts toward the theme stops meaning approved — but
        //    their lightness and their tint/border/text partners are built by
        //    the same rules as the brand, so they sit in the palette rather
        //    than beside it. Each solid is contrast-walked, so the label on a
        //    status badge is legible under every theme.
        foreach (self::SEMANTIC_HUES as $name => [$semHue, $semSat]) {
            $solid = self::darkenUntilReadable($semHue, $semSat, 0.46);

            $vars["--theme-$name"]           = $solid;
            $vars["--theme-$name-fg"]        = self::readableOn($solid, $ink);
            $vars["--theme-$name-subtle"]    = self::hsl($semHue, $semSat * 0.55, 0.955);
            $vars["--theme-$name-border"]    = self::hsl($semHue, $semSat * 0.60, 0.865);
            $vars["--theme-$name-emphasis"]  = self::hsl($semHue, $semSat, 0.28);
        }

        // ── 8. RGB triplets for the translucent layers — shadows, scrims,
        //    focus glows — which cannot be written with a hex variable.
        //    Without these, every `rgba(11, 4, 77, …)` shadow in the app
        //    stays navy under a green theme.
        $vars['--theme-primary-rgb'] = self::rgbTriplet($primary);
        $vars['--theme-accent-rgb']  = self::rgbTriplet($accent);
        $vars['--theme-ink-rgb']     = self::rgbTriplet($ink);
        $vars['--theme-shadow-rgb']  = self::rgbTriplet(self::hsl($h, $sat(0.55, 0.14, 0.55), 0.12));

        return $vars;
    }

    /**
     * One chrome surface and everything that sits on it.
     *
     * The surface is chosen by name; the label, the idle nav colour, the
     * hover fill and the divider are then *measured* from it. That is what
     * makes "Light" safe — the same rule that keeps white text off a pale
     * button keeps it off a pale sidebar.
     *
     * @param  'sidebar'|'topbar'  $name
     * @param  array<string,string>  $vars  the palette derived so far
     * @return array<string,string>
     */
    private static function surfaceVars(string $name, ?string $style, string $seed, array $vars): array
    {
        $style = isset(self::SURFACE_STYLES[$style]) ? $style : self::DEFAULT_SURFACE;
        [$h, $s] = self::hexToHsl($seed);
        $neutral = $s < 0.02;
        $sat = fn (float $f, float $min, float $max) => $neutral ? 0.0 : self::clamp($s * $f, $min, $max);

        $bg = match ($style) {
            // Near-black and near-white both keep a trace of the theme hue,
            // so a "Dark" sidebar under Emerald is not the same grey as one
            // under Crimson.
            'dark'  => self::hsl($h, $sat(0.35, 0.06, 0.22), 0.12),
            'light' => self::hsl($h, $sat(0.30, 0.04, 0.20), 0.985),
            default => $vars['--theme-primary'],
        };

        $fg = self::readableOn($bg, $vars['--theme-ink']);

        $surface = [
            "--theme-$name-bg"        => $bg,
            "--theme-$name-fg"        => $fg,
            // The stylesheets layer this surface's own colour at a dozen
            // different alphas (dividers, hovers, focus rings). A triplet
            // lets them keep doing that without hard-coding 255,255,255,
            // which is what stopped a light surface from being possible.
            "--theme-$name-fg-rgb"    => self::rgbTriplet($fg),
            // Idle nav labels: the surface's own text colour stepped back
            // toward it. Composited to a hex rather than left as rgba —
            // the surface is known here, so the real rendered colour can be
            // stated and therefore contrast-checked. An rgba() would only
            // look measurable.
            "--theme-$name-muted"     => self::stepBackFrom($fg, $bg),
            "--theme-$name-hover"     => self::rgba($fg, 0.08),
            "--theme-$name-active-bg" => self::rgba($fg, 0.14),
            "--theme-$name-border"    => self::rgba($fg, 0.12),
            // Readable back by JS so the preview can label the choice.
            "--theme-$name-style"     => $style,
        ];

        if ($name === 'topbar') {
            // The banner's glyph is the brand gold, which reads well on a
            // dark panel and disappears on a pale one. Keep the gold while it
            // clears the 3:1 floor for non-text, and fall back to the
            // surface's own label colour when it does not.
            $gold = $vars['--theme-warning'] ?? '#c9a227';
            $surface['--theme-topbar-icon'] = self::contrast($gold, $bg) >= self::AA_LARGE_CONTRAST
                ? $gold
                : $fg;
        }

        if ($name === 'sidebar') {
            // derive() published these before the surface was selectable and
            // the picker's own stylesheet still names them. They now follow
            // the chosen surface instead of assuming a dark brand fill.
            $surface['--theme-sidebar-text']   = $surface['--theme-sidebar-muted'];
            $surface['--theme-sidebar-active'] = $fg;
        }

        return $surface;
    }

    /**
     * Map the theme vocabulary onto the variable names the stylesheets
     * actually consume. `--gp-*` is the glass system's palette and
     * `--c-blue*` is admin.css's interactive ramp; both predate theming, so
     * the theme has to speak their names or nothing recolours.
     *
     * @param  array<string,string>  $vars
     * @return array<string,string>
     */
    private static function withConsumerAliases(array $vars): array
    {
        $vars['--gp-pri']       = $vars['--theme-primary'];
        $vars['--gp-pri-2']     = $vars['--theme-primary-2'];
        $vars['--gp-ink']       = $vars['--theme-ink'];
        $vars['--gp-muted']     = $vars['--theme-muted'];
        $vars['--gp-text-mid']  = $vars['--theme-text-mid'];
        $vars['--gp-text-soft'] = $vars['--theme-text-soft'];
        $vars['--gp-bg']        = $vars['--theme-bg'];
        $vars['--gp-bg-tint']   = $vars['--theme-bg-tint'];
        $vars['--gp-bg-tint-2'] = $vars['--theme-bg-tint-2'];
        $vars['--gp-border']    = $vars['--theme-border'];

        // admin.css already aliases --c-blue to --gp-pri; the accent is the
        // interactive colour, which is a lighter, more legible relative of
        // the anchor, so it is set explicitly rather than inherited.
        $vars['--c-blue']   = $vars['--theme-accent'];
        $vars['--c-blue-2'] = $vars['--theme-primary-2'];

        // The glass system's semantic trio predates the theme and is named
        // throughout the stylesheets, so the generated semantics have to
        // answer to those names or the status colours never move.
        $vars['--gp-good']        = $vars['--theme-success'];
        $vars['--gp-bad']         = $vars['--theme-danger'];
        $vars['--gp-accent-gold'] = $vars['--theme-warning'];

        // The settings page's own ramp, so it follows the active theme
        // instead of staying on its hard-coded blue.
        $vars['--set-blue']       = $vars['--theme-accent'];
        $vars['--set-blue-hover'] = self::shade($vars['--theme-accent'], -0.12);
        $vars['--set-blue-tint']  = $vars['--theme-primary-soft'];
        $vars['--set-blue-tint-2'] = $vars['--theme-primary-light'];
        $vars['--set-ring']       = $vars['--theme-focus-ring'];
        $vars['--set-line']       = $vars['--theme-border'];
        $vars['--set-line-soft']  = $vars['--theme-bg-tint'];

        return $vars;
    }

    // ─────────────────────────────────────────────────────────────────
    //  Colour maths
    // ─────────────────────────────────────────────────────────────────

    public static function isHex(?string $value): bool
    {
        return is_string($value) && preg_match('/^#[0-9a-fA-F]{6}$/', $value) === 1;
    }

    private static function clamp(float $value, float $min, float $max): float
    {
        return max($min, min($max, $value));
    }

    /** @return array{0:int,1:int,2:int} */
    private static function hexToRgb(string $hex): array
    {
        $hex = ltrim($hex, '#');

        return [
            (int) hexdec(substr($hex, 0, 2)),
            (int) hexdec(substr($hex, 2, 2)),
            (int) hexdec(substr($hex, 4, 2)),
        ];
    }

    /** @return array{0:float,1:float,2:float} hue in degrees, saturation and lightness in 0..1 */
    private static function hexToHsl(string $hex): array
    {
        [$r, $g, $b] = array_map(fn ($c) => $c / 255, self::hexToRgb($hex));

        $max = max($r, $g, $b);
        $min = min($r, $g, $b);
        $l   = ($max + $min) / 2;

        if ($max === $min) {
            return [0.0, 0.0, $l];
        }

        $d = $max - $min;
        $s = $l > 0.5 ? $d / (2 - $max - $min) : $d / ($max + $min);

        $h = match (true) {
            $max === $r => (($g - $b) / $d) + ($g < $b ? 6 : 0),
            $max === $g => (($b - $r) / $d) + 2,
            default     => (($r - $g) / $d) + 4,
        };

        return [$h * 60, $s, $l];
    }

    private static function hsl(float $h, float $s, float $l): string
    {
        $h = fmod(fmod($h, 360) + 360, 360) / 360;
        $s = self::clamp($s, 0, 1);
        $l = self::clamp($l, 0, 1);

        if ($s === 0.0) {
            $v = (int) round($l * 255);

            return sprintf('#%02x%02x%02x', $v, $v, $v);
        }

        $m2 = $l < 0.5 ? $l * (1 + $s) : $l + $s - $l * $s;
        $m1 = 2 * $l - $m2;

        $channel = function (float $t) use ($m1, $m2): int {
            $t = fmod(fmod($t, 1) + 1, 1);

            $v = match (true) {
                $t < 1 / 6 => $m1 + ($m2 - $m1) * 6 * $t,
                $t < 1 / 2 => $m2,
                $t < 2 / 3 => $m1 + ($m2 - $m1) * (2 / 3 - $t) * 6,
                default    => $m1,
            };

            return (int) round($v * 255);
        };

        return sprintf('#%02x%02x%02x', $channel($h + 1 / 3), $channel($h), $channel($h - 1 / 3));
    }

    /** WCAG 2.1 relative luminance. */
    private static function luminance(string $hex): float
    {
        $channels = array_map(function (int $c): float {
            $c = $c / 255;

            return $c <= 0.03928 ? $c / 12.92 : (($c + 0.055) / 1.055) ** 2.4;
        }, self::hexToRgb($hex));

        return 0.2126 * $channels[0] + 0.7152 * $channels[1] + 0.0722 * $channels[2];
    }

    /** WCAG contrast ratio, 1 (identical) to 21 (black on white). */
    public static function contrast(string $a, string $b): float
    {
        $la = self::luminance($a);
        $lb = self::luminance($b);

        return (max($la, $lb) + 0.05) / (min($la, $lb) + 0.05);
    }

    /**
     * The label colour for a filled surface: white when white is legible on
     * it, otherwise the theme's own ink. Measured, because "white on the
     * brand colour" stops being true the moment the brand colour is light.
     */
    private static function readableOn(string $background, string $ink): string
    {
        if (self::contrast($background, '#ffffff') >= self::AA_CONTRAST) {
            return '#ffffff';
        }

        if (self::contrast($background, $ink) >= self::AA_CONTRAST) {
            return $ink;
        }

        // Neither the theme's ink nor white clears AA on this surface — fall
        // back to whichever is further away rather than returning a colour
        // that is known-unreadable.
        return self::contrast($background, '#ffffff') >= self::contrast($background, $ink)
            ? '#ffffff'
            : '#111827';
    }

    /**
     * Walk a hue down in lightness until white text on it clears AA. Returns
     * the lightest passing shade, which keeps the action colour as vivid as
     * legibility allows instead of defaulting to something near-black.
     */
    private static function darkenUntilReadable(
        float $h,
        float $s,
        float $startL,
        float $minimum = self::AA_CONTRAST
    ): string {
        for ($l = $startL; $l >= 0.10; $l -= 0.01) {
            $candidate = self::hsl($h, $s, $l);

            if (self::contrast($candidate, '#ffffff') >= $minimum) {
                return $candidate;
            }
        }

        return self::hsl($h, $s, 0.10);
    }

    /**
     * Walk a hue up in lightness until it clears AA-large against the surface
     * it will sit on. Sidebar nav labels are the case: on a light seed the
     * "light tint of the brand" is not automatically readable.
     */
    private static function lightenUntilReadable(float $h, float $s, float $startL, string $on): string
    {
        for ($l = $startL; $l <= 0.97; $l += 0.01) {
            $candidate = self::hsl($h, $s, $l);

            if (self::contrast($candidate, $on) >= self::AA_LARGE_CONTRAST) {
                return $candidate;
            }
        }

        return self::hsl($h, $s * 0.5, 0.97);
    }

    /** Shift a colour's lightness; negative darkens. */
    private static function shade(string $hex, float $delta): string
    {
        [$h, $s, $l] = self::hexToHsl($hex);

        return self::hsl($h, $s, self::clamp($l + $delta, 0.04, 0.96));
    }

    private static function rgba(string $hex, float $alpha): string
    {
        [$r, $g, $b] = self::hexToRgb($hex);

        return sprintf('rgba(%d, %d, %d, %.2f)', $r, $g, $b, $alpha);
    }

    /** Blend two colours in sRGB. $weight is how much of $b to take. */
    private static function mix(string $a, string $b, float $weight): string
    {
        [$ar, $ag, $ab] = self::hexToRgb($a);
        [$br, $bg, $bb] = self::hexToRgb($b);
        $w = self::clamp($weight, 0, 1);

        return sprintf(
            '#%02x%02x%02x',
            (int) round($ar + ($br - $ar) * $w),
            (int) round($ag + ($bg - $ag) * $w),
            (int) round($ab + ($bb - $ab) * $w),
        );
    }

    /**
     * A de-emphasised version of $fg for use on $bg: stepped toward the
     * surface for hierarchy, then pulled back until it still clears
     * AA-large. Idle nav labels are the case — they should read as quieter
     * than the active one without becoming unreadable.
     */
    private static function stepBackFrom(string $fg, string $bg): string
    {
        for ($w = 0.28; $w >= 0.0; $w -= 0.04) {
            $candidate = self::mix($fg, $bg, $w);

            if (self::contrast($candidate, $bg) >= self::AA_LARGE_CONTRAST) {
                return $candidate;
            }
        }

        return $fg;
    }

    /** "11, 4, 77" — for `rgba(var(--theme-…-rgb), .3)` in the stylesheets. */
    private static function rgbTriplet(string $hex): string
    {
        return implode(', ', self::hexToRgb($hex));
    }
}
