<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DesignationSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $designations = [
            ['title' => 'Municipal Mayor', 'department_id' => 1, 'salary_grade' => null, 'monthly_rate' => 121264.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Executive Asst. II', 'department_id' => 1, 'salary_grade' => null, 'monthly_rate' => 40160.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Private Sec. II', 'department_id' => 1, 'salary_grade' => null, 'monthly_rate' => 34177.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 1, 'salary_grade' => null, 'monthly_rate' => 21922.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 1, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Personal Driver', 'department_id' => 1, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'BAC Sec./ Admin Officer IV', 'department_id' => 4, 'salary_grade' => null, 'monthly_rate' => 34177.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Administrator', 'department_id' => 5, 'salary_grade' => null, 'monthly_rate' => 83457.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => "Proj. Dev't. Officer III", 'department_id' => 6, 'salary_grade' => null, 'monthly_rate' => 43608.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Zoning Officer I', 'department_id' => 6, 'salary_grade' => null, 'monthly_rate' => 25520.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 6, 'salary_grade' => null, 'monthly_rate' => 21748.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 6, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Asst. IV', 'department_id' => 7, 'salary_grade' => null, 'monthly_rate' => 21922.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Clerk IV', 'department_id' => 7, 'salary_grade' => null, 'monthly_rate' => 18563.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Supply Officer I', 'department_id' => 8, 'salary_grade' => null, 'monthly_rate' => 21748.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Asst. IV', 'department_id' => 8, 'salary_grade' => null, 'monthly_rate' => 21748.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Laborer II', 'department_id' => 8, 'salary_grade' => null, 'monthly_rate' => 14189.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 8, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 8, 'salary_grade' => null, 'monthly_rate' => 13575.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Budget Officer', 'department_id' => 9, 'salary_grade' => null, 'monthly_rate' => 83457.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin Asst.V', 'department_id' => 9, 'salary_grade' => null, 'monthly_rate' => 25520.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Budget Officer I', 'department_id' => 9, 'salary_grade' => null, 'monthly_rate' => 25762.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 9, 'salary_grade' => null, 'monthly_rate' => 21922.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 9, 'salary_grade' => null, 'monthly_rate' => 14414.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 9, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Accountant', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 93016.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Computer Operator IV', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 31776.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mgt. and Audit Analyst', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 25520.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookkeeper III', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 22810.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookkeeper III', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 21748.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 21748.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Acctg. Clerk II', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 16113.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 14521.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 10, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Treasurer', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 90205.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Asst. Mun. Treasurer', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 67385.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'LRCO III', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 44057.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Cashier II', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 31470.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 21922.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'RCC II', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 17735.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'RCC II', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 17219.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'RCC II', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 17094.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Lic. Inspector', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 16113.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 13575.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 11, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Assessor', 'department_id' => 12, 'salary_grade' => null, 'monthly_rate' => 88811.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Local Assessment Operations Officer II', 'department_id' => 12, 'salary_grade' => null, 'monthly_rate' => 34513.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Assessment Clerk III', 'department_id' => 12, 'salary_grade' => null, 'monthly_rate' => 19899.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Assessment Clerk II', 'department_id' => 12, 'salary_grade' => null, 'monthly_rate' => 16113.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 12, 'salary_grade' => null, 'monthly_rate' => 14521.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 12, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Health Officer', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 109431.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Public Health Nurse', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 50735.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Nurse II', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 43996.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Nurse I', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 40604.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'MedTech', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 40604.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Computer Operator IV', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 37384.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Midwife IV', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 34421.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Midwife III', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 30308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Midwife III', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 30024.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Data Encoder III', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 30308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Sanitary Inspector II', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 22035.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Clerk IV', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 21642.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Nursing Attendant II', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 18957.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Sanitary Inspector I', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 18957.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 17209.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Driver II', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 16833.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 16088.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 13, 'salary_grade' => null, 'monthly_rate' => 15852.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 14, 'salary_grade' => null, 'monthly_rate' => 13575.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 15, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'SWOII- OIC MSWDO', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 34855.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Daycare Worker II', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 19417.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Daycare Worker I', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 18563.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Social Welfare Asst.', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 18396.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Daycare Worker I', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 16969.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Daycare Worker I', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 16233.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Daycare Worker I', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 16113.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Social Welfare Aide I', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 14521.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Social Welfare Aide I', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 14414.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Social Welfare Aide I', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 16, 'salary_grade' => null, 'monthly_rate' => 13575.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Agriculturist II- OIC Mun. Agriculturist', 'department_id' => 17, 'salary_grade' => null, 'monthly_rate' => 34177.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Agriculturist I', 'department_id' => 17, 'salary_grade' => null, 'monthly_rate' => 25520.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Farm Supervisor', 'department_id' => 17, 'salary_grade' => null, 'monthly_rate' => 18563.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Farm Foreman', 'department_id' => 17, 'salary_grade' => null, 'monthly_rate' => 16113.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 17, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 17, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'MGDH I', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 83457.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Driver II', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 14521.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Laborer II', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 14189.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Laborer II', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 13357.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 13575.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 18, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Engr.', 'department_id' => 19, 'salary_grade' => null, 'monthly_rate' => 90205.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Engr. II', 'department_id' => 19, 'salary_grade' => null, 'monthly_rate' => 37026.00, 'employment_type' => 'Permanent', 'description' => null],
            ["title" => "Eng'g. Aide II", 'department_id' => 19, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 19, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 19, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Mun. Tourism Operations Officer', 'department_id' => 20, 'salary_grade' => null, 'monthly_rate' => 87440.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Foreman B', 'department_id' => 20, 'salary_grade' => null, 'monthly_rate' => 18730.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Laborer II', 'department_id' => 20, 'salary_grade' => null, 'monthly_rate' => 14189.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Laborer II', 'department_id' => 20, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 20, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 20, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Laborer II', 'department_id' => 21, 'salary_grade' => null, 'monthly_rate' => 13675.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide I', 'department_id' => 22, 'salary_grade' => null, 'monthly_rate' => 11952.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Laborer II', 'department_id' => 22, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder III', 'department_id' => 23, 'salary_grade' => null, 'monthly_rate' => 17094.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 23, 'salary_grade' => null, 'monthly_rate' => 14414.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 23, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 23, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Municipal Vice Mayor', 'department_id' => 24, 'salary_grade' => null, 'monthly_rate' => 94968.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Executive Asst. I', 'department_id' => 24, 'salary_grade' => null, 'monthly_rate' => 31470.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Private Sec. I', 'department_id' => 24, 'salary_grade' => null, 'monthly_rate' => 25520.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Personal Driver', 'department_id' => 24, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide I', 'department_id' => 24, 'salary_grade' => null, 'monthly_rate' => 12039.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'SB Member', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 84763.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'SB Member', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 83457.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'SB Member', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 87440.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin Officer V', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 44057.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 22097.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 13575.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 25, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'SB Secretary', 'department_id' => 26, 'salary_grade' => null, 'monthly_rate' => 93016.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Record Ofcr. I', 'department_id' => 26, 'salary_grade' => null, 'monthly_rate' => 22097.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 26, 'salary_grade' => null, 'monthly_rate' => 21748.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Asst. II', 'department_id' => 26, 'salary_grade' => null, 'monthly_rate' => 18231.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Local Legislative Staff I', 'department_id' => 26, 'salary_grade' => null, 'monthly_rate' => 16233.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'MGDH I', 'department_id' => 3, 'salary_grade' => null, 'monthly_rate' => 86091.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Bookbinder IV', 'department_id' => 3, 'salary_grade' => null, 'monthly_rate' => 21922.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide IV', 'department_id' => 3, 'salary_grade' => null, 'monthly_rate' => 14308.00, 'employment_type' => 'Permanent', 'description' => null],
            ['title' => 'Admin. Aide III', 'department_id' => 3, 'salary_grade' => null, 'monthly_rate' => 13474.00, 'employment_type' => 'Permanent', 'description' => null],
        ];

        // Chunk inserts to stay safe with large batches and add timestamps
        collect($designations)->chunk(100)->each(function ($chunk) use ($now) {
            $rows = $chunk->map(function ($item) use ($now) {
                return array_merge($item, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            })->toArray();

            DB::table('designations')->insert($rows);
        });
    }
}